---
title: "Syphilis screening final"
output: html_document
date: "2023-07-28"
---

```{r}
library(sf)
library(purrr)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(readr)
library(survey)
```

```{r}
data_ubigeo <- read_csv("Data_final/data_ubigeo_innovalab.csv")
data_ubigeo_2022_innova <- read_csv("Data_final/data_ubigeo_2022_innova.csv")
provincias <- read_sf("Límites - mapas/PROVINCIAS_inei_geogpsperu_suyopomalia.shp")
departamentos <- read_sf("Límites - mapas/DEPARTAMENTOS_inei_geogpsperu_suyopomalia.shp")
data_syphilis <- read_csv("Data_final/data_syphilis.csv")
```

```{r}
#write.csv(data_ubigeo_macroregion,"./Data_final/data_ubigeo_macroregion.csv", row.names = F)
```

```{r}
data_ubigeo_2022_innova = data_ubigeo_2022_innova[,c(2:6,1,7:9)]
data_ubigeo = data_ubigeo[,c(1:6,8,10,12)]

data_ubigeo_2022_innova = rename(data_ubigeo_2022_innova, c("NOMBDEP"="DEPARTAMEN","NOMBPROV"="PROVINCIA","NOMBDIST"="DISTRITO"))

data_ubigeo = rbind(data_ubigeo,data_ubigeo_2022_innova)
```

#####
##Agrupación de regiones: https://www.inei.gob.pe/media/MenuRecursivo/boletines/indicador_de_la_produccion_departamental.pdf

```{r}
data_ubigeo_macroregion = data_ubigeo %>%
  mutate(
  ZONA= ifelse(NOMBDEP=="LIMA"|NOMBDEP=="CALLAO",1,
               ifelse(NOMBDEP=="TUMBES"|NOMBDEP=="PIURA"|NOMBDEP=="LAMBAYEQUE"|NOMBDEP=="LA LIBERTAD"|NOMBDEP=="CAJAMARCA",2,
                      ifelse(NOMBDEP=="ANCASH"|NOMBDEP=="HUANUCO"|NOMBDEP=="PASCO"|NOMBDEP=="JUNIN"|NOMBDEP=="HUANCAVELICA"|NOMBDEP=="ICA"|NOMBDEP=="AYACUCHO",3,
                             ifelse(NOMBDEP=="AREQUIPA"|NOMBDEP=="APURIMAC"|NOMBDEP=="CUSCO"|NOMBDEP=="PUNO"|NOMBDEP=="MOQUEGUA"|NOMBDEP=="TACNA",4,
                                    ifelse(NOMBDEP=="LORETO"|NOMBDEP=="SAN MARTIN"|NOMBDEP=="UCAYALI"|NOMBDEP=="MADRE DE DIOS"|NOMBDEP == "CAJAMARCA"|NOMBDEP == "AMAZONAS",5,NA))))
))
```

```{r}
rm(data_ubigeo_2022_innova)
```

```{r}
data_total <- data_syphilis%>% 
  left_join(data_ubigeo_macroregion, by = c("caseid","year"))

data_total <- data_total %>%
  left_join(departamentos, by = c("NOMBDEP"))
```

```{r}
rm(data_ubigeo_macroregion,data_ubigeo,data_syphilis)
```

```{r}
# Filtrar los datos
data_filtered <- data_total %>%
  mutate(
    syphilis_screening=ifelse(syphilis_screening=="Yes",1, 0)
  )

data_filtered$syphilis_screening <- ifelse(is.na(data_filtered$syphilis_screening),0,data_filtered$syphilis_screening)

data_filtered$NOMBDEP = as.factor(data_filtered$NOMBDEP)
data_filtered$year = as.factor(data_filtered$year)

data_filtered = data_filtered %>%
  filter(year!=2010&year!=2011&year!=2012&year!=2013&year!=2014)

# Crear el diseño de muestreo estratificado
design <- svydesign(id = ~ v001, strata = ~ v022, nest = TRUE, weights = ~ v005, data = data_filtered, na.rm = TRUE)

options(survey.lonely.psu="adjust")

syphilis_year<- svyby(~syphilis_screening,~NOMBDEP+year+ZONA,svymean,design=design,na.rm=TRUE)
syphilis_total<- svyby(~syphilis_screening,~NOMBDEP+ZONA,svymean,design=design,na.rm=TRUE)
syphilis_provincias<- svyby(~syphilis_screening,~NOMBPROV+year+ZONA,svymean,design=design,na.rm=TRUE)
syphilis_general <- svyby(~syphilis_screening,~year,svymean,design=design,na.rm=TRUE)

syphilis_year = as.data.frame(syphilis_year)
syphilis_total = as.data.frame(syphilis_total)
syphilis_provincias = as.data.frame(syphilis_provincias)
syphilis_general = as.data.frame(syphilis_general)
```

```{r}
data_grafico_prov <- syphilis_provincias  %>%
  left_join(provincias, by = c("NOMBPROV"))
```

```{r}
data_grafico_total <- syphilis_total  %>%
  left_join(departamentos, by = c("NOMBDEP"))
```

Total
```{r}
ggplot() +
  geom_sf(data = data_grafico_total, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening total",
        fill = "Syphilis screening") 
```

```{r}
data_grafico_year <- syphilis_year  %>%
  left_join(departamentos, by = c("NOMBDEP"))
```

```{r}
rm(departamentos,provincias,syphilis_year,syphilis_provincias,design,data_filtered,data_total)
```


2015
```{r}
data_grafico_2015 = data_grafico_year %>%
  filter(year==2015)

ggplot() +
  geom_sf(data = data_grafico_2015, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2015",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2015)
```

2016
```{r}
data_grafico_2016 = data_grafico_year %>%
  filter(year==2016)

ggplot() +
  geom_sf(data = data_grafico_2016, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2016",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2016)
```

2017
```{r}
data_grafico_2017 = data_grafico_year %>%
  filter(year==2017)

ggplot() +
  geom_sf(data = data_grafico_2017, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2017",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2017)
```

2018
```{r}
data_grafico_2018 = data_grafico_year %>%
  filter(year==2018)

ggplot() +
  geom_sf(data = data_grafico_2018, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2018",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2018)
```

2019
```{r}
data_grafico_2019 = data_grafico_year %>%
  filter(year==2019)

ggplot() +
  geom_sf(data = data_grafico_2019, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2019",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2019)
```

2020
```{r}
data_grafico_2020 = data_grafico_year %>%
  filter(year==2020)

ggplot() +
  geom_sf(data = data_grafico_2020, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2020",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2020)
```

2021
```{r}
data_grafico_2021 = data_grafico_year %>%
  filter(year==2021)

ggplot() +
  geom_sf(data = data_grafico_2021, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2021",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2021)
```

2022
```{r}
data_grafico_2022 = data_grafico_year %>%
  filter(year==2022)

ggplot() +
  geom_sf(data = data_grafico_2022, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.2) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
   labs(title="Syphilis screening 2022",
        fill = "Syphilis screening")

```

```{r}
rm(data_grafico_2022)
```

```{r, fig.height=7, fig.width=9}
figureS3 <- ggplot() +
  geom_sf(data = data_grafico_year, aes(geometry = geometry,fill = syphilis_screening), color = "black", size = 0.4) +
  scale_fill_gradient(low = "#D2EEEA", high = "#2A5676") +
  facet_wrap(~year)+
  labs(fill = "Rate") + 
  theme_minimal() +
  theme(
    axis.text = element_blank(),       
    axis.ticks = element_blank(),     
    axis.title = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )

print(figureS3)

ggsave("Trends_2015-2022_S3.png", plot = figureS3, width = 7, height = 8, dpi = 300)
```

Grafico dumbbell general: syphilis_screening

```{r}
dtotal = data_grafico_year %>%
  filter(year==2015|year==2018|year==2022) 

dtotal <- dtotal %>%
  group_by(NOMBDEP) %>%
  mutate(screening_2022 = max(syphilis_screening[year == 2022], na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(NOMBDEP = reorder(NOMBDEP, -screening_2022))

d15_d22_screening <- 
  ggplot(dtotal, aes(x = syphilis_screening, y = NOMBDEP)) +
  geom_line() +
  geom_point(aes(color = year), size = 3) +
  geom_vline(xintercept = 0.95,color = "black", linetype = "dashed", size=1.2) +
  scale_color_manual(values = c("#EACB2B", "#3B99B1" , "#F5191C")) +
  labs(title = "Syphilis screening") +
  xlab("Prop%")+
  ylab("Deparments") +
  theme_bw() +
  theme(
    axis.title = element_text(face ="bold", size = 15),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    plot.title = element_text(size = 17),
    legend.text = element_text(size = 14, face = "bold"),
    axis.text = element_text(face = "bold", family = "Arial"),
    axis.text.x = element_text(size = 12),
    legend.position = "right",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", linewidth = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank()
  ) 

#ggsave("Graph_dumbell_3a.png", plot = d15_d22_screening, width = 8, height = 4, dpi = 300)
print(d15_d22_screening)
```

