---
title: "Home, prenatal care"
author: "Jazmín Qquellon"
date: "2023-07-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(readr)
library(tidyverse)
data <- read_csv("Data_final/data_syphilis.csv")
```


```{r}
#Type of residence

#Total
residence_total <- data %>%
   dplyr::group_by(type_residence) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_residence_2010 <- subset(data, year == 2010)

# Agrupar los datos
residence_2010 <- sub_residence_2010  %>%
  dplyr::group_by(type_residence) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_residence_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_residence_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_residence_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_residence_2010)

# 2016
sub_residence_2016 <- subset(data, year == 2016)

# Agrupar los datos 
residence_2016 <- sub_residence_2016  %>%
  dplyr::group_by(type_residence) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_residence_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_residence_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_residence_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_residence_2016)

# 2022
sub_residence_2022 <- subset(data, year == 2022)

# Agrupar los datos
residence_2022 <- sub_residence_2022  %>%
  dplyr::group_by(type_residence) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_residence_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_residence_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_residence_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_residence_2022)

```

```{r}
rm(residence_total,residence_2010, residence_2016, residence_2022)
```

```{r}
#Natural region

#Total
region_total <- data %>%
   dplyr::group_by(natural_region) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_region_2010 <- subset(data, year == 2010)

# Agrupar los datos
region_2010 <- sub_region_2010  %>%
  dplyr::group_by(natural_region) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_region_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_region_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_region_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_region_2010)

# 2016
sub_region_2016 <- subset(data, year == 2016)

# Agrupar los datos
region_2016 <- sub_region_2016  %>%
  dplyr::group_by(natural_region) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_region_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_region_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_region_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_region_2016)

# 2022
sub_region_2022 <- subset(data, year == 2022)

# Agrupar los datos
region_2022 <- sub_region_2022  %>%
  dplyr::group_by(natural_region) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_region_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_region_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_region_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_region_2022)
```

```{r}
rm(region_total,region_2010, region_2016, region_2022)
```

```{r}
#Wealth index

#Total
wealth_total <- data %>%
   dplyr::group_by(wealth_index) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_wealth_2010 <- subset(data, year == 2010)

# Agrupar los datos
wealth_2010 <- sub_wealth_2010  %>%
  dplyr::group_by(wealth_index) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_wealth_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_wealth_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_wealth_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_wealth_2010)

# 2016
sub_wealth_2016 <- subset(data, year == 2016)

# Agrupar los datos 
wealth_2016 <- sub_wealth_2016  %>%
  dplyr::group_by(wealth_index) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_wealth_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_wealth_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_wealth_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_wealth_2016)

# 2022
sub_wealth_2022 <- subset(data, year == 2022)

# Agrupar los datos 
wealth_2022 <- sub_wealth_2022  %>%
  dplyr::group_by(wealth_index) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_wealth_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_wealth_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_wealth_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_wealth_2022)
```

```{r}
rm(wealth_total,wealth_2010, wealth_2016, wealth_2022)
```

```{r}
#Relationship with household head

#Total
household_total <- data %>%
   dplyr::group_by(relationship_household_head) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_household_2010 <- subset(data, year == 2010)

# Agrupar los datos 
household_2010 <- sub_household_2010  %>%
  dplyr::group_by(relationship_household_head) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_household_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_household_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_household_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_household_2010)

# 2016
sub_household_2016 <- subset(data, year == 2016)

# Agrupar los datos 
household_2016 <- sub_household_2016  %>%
  dplyr::group_by(relationship_household_head) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_household_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_household_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_household_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_household_2016)

# 2022
sub_household_2022 <- subset(data, year == 2022)

# Agrupar los datos
household_2022 <- sub_household_2022  %>%
  dplyr::group_by(relationship_household_head) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_household_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_household_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_household_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_household_2022)
```

```{r}
rm(household_total,household_2010, household_2016, household_2022)
```

```{r}
#Total members household

#Total
members_total <- data %>%
   dplyr::group_by(members_household) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_members_2010 <- subset(data, year == 2010)

# Agrupar los datos 
members_2010 <- sub_members_2010  %>%
  dplyr::group_by(members_household) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_members_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_members_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_members_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_members_2010)

# 2016
sub_members_2016 <- subset(data, year == 2016)

# Agrupar los datos 
members_2016 <- sub_members_2016  %>%
  dplyr::group_by(members_household) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_members_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_members_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_members_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_members_2016)

# 2022
sub_members_2022 <- subset(data, year == 2022)

# Agrupar los datos
members_2022 <- sub_members_2022  %>%
  dplyr::group_by(members_household) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_members_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_members_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_members_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_members_2022)
```

```{r}
rm(members_total,members_2010, members_2016, members_2022)
```

```{r}
#Social programs: Juntos

#Total
sub_juntos_total <- subset(data, year== 2014 | year==2015 | year==2016 | year==2017 | year==2018 | year==2019 | year==2020 | year==2021 | year==2022)

juntos_total <- sub_juntos_total %>%
   dplyr::group_by(juntos) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_juntos_total) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_juntos_total), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_juntos_total), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_juntos_total)
   
# 2010
sub_juntos_2010 <- subset(data, year == 2010)

# Agrupar los datos 
juntos_2010 <- sub_juntos_2010  %>%
  dplyr::group_by(juntos) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_juntos_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_juntos_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_juntos_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_juntos_2010)

# 2016
sub_juntos_2016 <- subset(data, year == 2016)

# Agrupar los datos 
juntos_2016 <- sub_juntos_2016  %>%
  dplyr::group_by(juntos) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_juntos_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_juntos_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_juntos_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_juntos_2016)

# 2022
sub_juntos_2022 <- subset(data, year == 2022)

# Agrupar los datos
juntos_2022 <- sub_juntos_2022  %>%
  dplyr::group_by(juntos) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_juntos_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_juntos_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_juntos_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_juntos_2022)
```

```{r}
rm(juntos_total,juntos_2010, juntos_2016, juntos_2022)
```

```{r}
#Social programs: Wawa wasi

sub_wawa_total <- subset(data, year== 2014 | year==2015 | year==2016 | year==2017 | year==2018 | year==2019 | year==2020 | year==2021 | year==2022)
#Total
wawa_total <- sub_wawa_total %>%
   dplyr::group_by(wawa_wasi) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_wawa_total) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_wawa_total), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_wawa_total), conf.level = 0.95)$conf.int[2] * 100,1))
  
rm(sub_wawa_total)

# 2010
sub_wawa_2010 <- subset(data, year == 2010)

# Agrupar los datos 
wawa_2010 <- sub_wawa_2010  %>%
  dplyr::group_by(wawa_wasi) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_wawa_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_wawa_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_wawa_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_wawa_2010)

# 2016
sub_wawa_2016 <- subset(data, year == 2016)

# Agrupar los datos 
wawa_2016 <- sub_wawa_2016  %>%
  dplyr::group_by(wawa_wasi) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_wawa_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_wawa_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_wawa_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_wawa_2016)

# 2022
sub_wawa_2022 <- subset(data, year == 2022)

# Agrupar los datos
wawa_2022 <- sub_wawa_2022  %>%
  dplyr::group_by(wawa_wasi) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_wawa_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_wawa_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_wawa_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_wawa_2022)
```

```{r}
rm(wawa_total,wawa_2010, wawa_2016, wawa_2022)
```

```{r}
#Health insurance

#Total
insurance_total <- data %>%
   dplyr::group_by(health_insurance) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_insurance_2010 <- subset(data, year == 2010)

# Agrupar los datos 
insurance_2010 <- sub_insurance_2010  %>%
  dplyr::group_by(health_insurance) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_insurance_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_insurance_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_insurance_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_insurance_2010)

# 2016
sub_insurance_2016 <- subset(data, year == 2016)

# Agrupar los datos 
insurance_2016 <- sub_insurance_2016  %>%
  dplyr::group_by(health_insurance) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_insurance_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_insurance_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_insurance_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_insurance_2016)

# 2022
sub_insurance_2022 <- subset(data, year == 2022)

# Agrupar los datos
insurance_2022 <- sub_insurance_2022  %>%
  dplyr::group_by(health_insurance) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_insurance_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_insurance_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_insurance_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_insurance_2022)
```

```{r}
rm(insurance_total,insurance_2010, insurance_2016, insurance_2022)
```

```{r}
#place of prenatal care

#Total
place_total <- data %>%
   dplyr::group_by(place_prenatal_care) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_place_2010 <- subset(data, year == 2010)

# Agrupar los datos 
place_2010 <- sub_place_2010  %>%
  dplyr::group_by(place_prenatal_care) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_place_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_place_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_place_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_place_2010)

# 2016
sub_place_2016 <- subset(data, year == 2016)

# Agrupar los datos 
place_2016 <- sub_place_2016  %>%
  dplyr::group_by(place_prenatal_care) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_place_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_place_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_place_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_place_2016)

# 2022
sub_place_2022 <- subset(data, year == 2022)

# Agrupar los datos
place_2022 <- sub_place_2022  %>%
  dplyr::group_by(place_prenatal_care) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_place_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_place_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_place_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_place_2022)
```

```{r}
rm(place_total,place_2010, place_2016, place_2022)
```

```{r}
#professional level of prenatal care

#Total
provider_total <- data %>%
   dplyr::group_by(prenatal_care_provider) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_provider_2010 <- subset(data, year == 2010)

# Agrupar los datos 
provider_2010 <- sub_provider_2010  %>%
  dplyr::group_by(prenatal_care_provider) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_provider_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_provider_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_provider_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_provider_2010)

# 2016
sub_provider_2016 <- subset(data, year == 2016)

# Agrupar los datos 
provider_2016 <- sub_provider_2016  %>%
  dplyr::group_by(prenatal_care_provider) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_provider_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_provider_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_provider_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_provider_2016)

# 2022
sub_provider_2022 <- subset(data, year == 2022)

# Agrupar los datos
provider_2022 <- sub_provider_2022  %>%
  dplyr::group_by(prenatal_care_provider) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_provider_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_provider_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_provider_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_provider_2022)
```

```{r}
rm(provider_total, provider_2010, provider_2016, provider_2022)
```

```{r}
#Size of child at birth

#Total
size_total <- data %>%
   mutate(size_final = case_when(
      size_birth == "large"| size_birth == "very large"  ~ "large/very large",
      size_birth == "normal" ~ "normal",
      size_birth == "small"| size_birth == "very_small"  ~ "small/very small",
      TRUE ~ NA
    )) %>%
   dplyr::group_by(size_final) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_size_2010 <- subset(data, year == 2010)

# Agrupar los datos 
size_2010 <- sub_size_2010  %>%
     mutate(size_final = case_when(
      size_birth == "large"| size_birth == "very large"  ~ "large/very large",
      size_birth == "normal" ~ "normal",
      size_birth == "small"| size_birth == "very_small"  ~ "small/very small",
      TRUE ~ NA
    )) %>%
  dplyr::group_by(size_final) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_size_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_size_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_size_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_size_2010)

# 2016
sub_size_2016 <- subset(data, year == 2016)

# Agrupar los datos 
size_2016 <- sub_size_2016  %>%
     mutate(size_final = case_when(
      size_birth == "large"| size_birth == "very large"  ~ "large/very large",
      size_birth == "normal" ~ "normal",
      size_birth == "small"| size_birth == "very_small"  ~ "small/very small",
      TRUE ~ NA
    )) %>%
  dplyr::group_by(size_final) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_size_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_size_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_size_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_size_2016)

# 2022
sub_size_2022 <- subset(data, year == 2022)

# Agrupar los datos
size_2022 <- sub_size_2022  %>%
     mutate(size_final = case_when(
      size_birth == "large"| size_birth == "very large"  ~ "large/very large",
      size_birth == "normal" ~ "normal",
      size_birth == "small"| size_birth == "very_small"  ~ "small/very small",
      TRUE ~ NA
    )) %>%
  dplyr::group_by(size_final) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_size_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_size_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_size_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_size_2022)
```

```{r}
rm(size_total, size_2010, size_2016, size_2022)
```

```{r}
#Weight of child at birth

#Total
weight_total <- data %>%
  dplyr::group_by(weight_birth) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(data) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(data), conf.level = 0.95)$conf.int[2] * 100,1))
  
# 2010
sub_weight_2010 <- subset(data, year == 2010)

# Agrupar los datos 
weight_2010 <- sub_weight_2010  %>%
  dplyr::group_by(weight_birth) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_weight_2010) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_weight_2010), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_weight_2010), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_weight_2010)

# 2016
sub_weight_2016 <- subset(data, year == 2016)

# Agrupar los datos 
weight_2016 <- sub_weight_2016  %>%
  dplyr::group_by(weight_birth) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_weight_2016) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_weight_2016), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_weight_2016), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_weight_2016)

# 2022
sub_weight_2022 <- subset(data, year == 2022)

# Agrupar los datos
weight_2022 <- sub_weight_2022  %>%
  dplyr::group_by(weight_birth) %>%
  dplyr::summarise(total_observaciones = n(),
            porcentaje = round(total_observaciones / nrow(sub_weight_2022) * 100,1),
            intervalo_confianza_inf = round(prop.test(total_observaciones, nrow(sub_weight_2022), conf.level = 0.95)$conf.int[1] * 100,1),
            intervalo_confianza_sup = round(prop.test(total_observaciones, nrow(sub_weight_2022), conf.level = 0.95)$conf.int[2] * 100,1))

rm(sub_weight_2022)
```

```{r}
rm(weight_total, weight_2010, weight_2016, weight_2022)
```

```{r}
#MONTHS OF THE FIRST PRENATAL VISIT
month_total <- data %>%
  summarise(mediana = median(first_prenatal_visit_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(first_prenatal_visit_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(first_prenatal_visit_1, 0.75, na.rm = TRUE))

#AGE FIRST SEXUAL INTERCOURSE 2010
year_ = 2010
datos_filtrados <- filter(data, year == year_)
total_general <- nrow(datos_filtrados)

month_2010 <- datos_filtrados %>%
  summarise(mediana = median(first_prenatal_visit_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(first_prenatal_visit_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(first_prenatal_visit_1, 0.75, na.rm = TRUE))

rm(year_,datos_filtrados)

#AGE FIRST SEXUAL INTERCOURSE 2016
year_ = 2016
datos_filtrados <- filter(data, year == year_)
total_general <- nrow(datos_filtrados)

month_2016 <- datos_filtrados %>%
  summarise(mediana = median(first_prenatal_visit_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(first_prenatal_visit_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(first_prenatal_visit_1, 0.75, na.rm = TRUE))

rm(year_,datos_filtrados)

#AGE FIRST SEXUAL INTERCOURSE 2022
year_ = 2022
datos_filtrados <- filter(data, year == year_)
total_general <- nrow(datos_filtrados)

month_2022 <- datos_filtrados %>%
  summarise(mediana = median(first_prenatal_visit_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(first_prenatal_visit_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(first_prenatal_visit_1, 0.75, na.rm = TRUE))

rm(year_,datos_filtrados)
```

```{r}
rm(month_total,month_2010, month_2016, month_2022)
```

```{r}
#NUMBER OF THE PRENATAL VISITS
number_total <- data %>%
  summarise(mediana = median(number_prenatal_visits_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(number_prenatal_visits_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(number_prenatal_visits_1, 0.75, na.rm = TRUE))

#AGE FIRST SEXUAL INTERCOURSE 2010
year_ = 2010
datos_filtrados <- filter(data, year == year_)
total_general <- nrow(datos_filtrados)

number_2010 <- datos_filtrados %>%
  summarise(mediana = median(number_prenatal_visits_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(number_prenatal_visits_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(number_prenatal_visits_1, 0.75, na.rm = TRUE))

rm(year_,datos_filtrados)

#AGE FIRST SEXUAL INTERCOURSE 2016
year_ = 2016
datos_filtrados <- filter(data, year == year_)
total_general <- nrow(datos_filtrados)

number_2016 <- datos_filtrados %>%
  summarise(mediana = median(number_prenatal_visits_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(number_prenatal_visits_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(number_prenatal_visits_1, 0.75, na.rm = TRUE))

rm(year_,datos_filtrados)

#AGE FIRST SEXUAL INTERCOURSE 2022
year_ = 2022
datos_filtrados <- filter(data, year == year_)
total_general <- nrow(datos_filtrados)

number_2022 <- datos_filtrados %>%
  summarise(mediana = median(number_prenatal_visits_1, na.rm=TRUE),
         Intervalo_Confianza_Inf = quantile(number_prenatal_visits_1, 0.25, na.rm = TRUE),
            Intervalo_Confianza_Sup = quantile(number_prenatal_visits_1, 0.75, na.rm = TRUE))

rm(year_,datos_filtrados)
```

```{r}
rm(number_total,number_2010, number_2016, number_2022)
```

