---
title: "Mapas I"
output: html_document
date: "2023-07-28"
---

```{r}
library(sf)
library(purrr)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(readr)
library(survey)
```

```{r}
data_ubigeo <- read_csv("Data_final/data_ubigeo_innovalab.csv")
data_ubigeo_2022_innova <- read_csv("Data_final/data_ubigeo_2022_innova.csv")
provincias <- read_sf("Límites - mapas/PROVINCIAS_inei_geogpsperu_suyopomalia.shp")
departamentos <- read_sf("Límites - mapas/DEPARTAMENTOS_inei_geogpsperu_suyopomalia.shp")
data_syphilis <- read_csv("Data_final/data_syphilis.csv")
```

```{r}
#write.csv(data_ubigeo_macroregion,"./Data_final/data_ubigeo_macroregion.csv", row.names = F)
```

```{r}
data_ubigeo_2022_innova = data_ubigeo_2022_innova[,c(2:6,1,7:9)]
data_ubigeo = data_ubigeo[,c(1:6,8,10,12)]

data_ubigeo_2022_innova = rename(data_ubigeo_2022_innova, c("NOMBDEP"="DEPARTAMEN","NOMBPROV"="PROVINCIA","NOMBDIST"="DISTRITO"))

data_ubigeo = rbind(data_ubigeo,data_ubigeo_2022_innova)
```

```{r}
data_ubigeo_macroregion = data_ubigeo %>%
mutate(
  Macrozona = ifelse(NOMBDEP=="TUMBES"|NOMBDEP=="PIURA"|NOMBDEP=="LAMBAYEQUE"|NOMBDEP=="LA LIBERTAD"|NOMBDEP=="ANCASH"| NOMBDEP=="CAJAMARCA"&NOMBPROV!="SAN IGNACIO"|NOMBDEP=="CAJAMARCA"&NOMBPROV!="JAEN"| NOMBDEP=="AMAZONAS"&NOMBPROV=="LUYA"|NOMBDEP=="AMAZONAS"&NOMBPROV=="CHACHAPOYAS", "Norte", ifelse(NOMBDEP=="LORETO"|NOMBDEP=="UCAYALI"|NOMBDEP=="SAN MARTIN"|NOMBDEP=="MADRE DE DIOS"|NOMBDEP=="CAJAMARCA"&NOMBPROV=="SAN IGNACIO"|NOMBDEP=="CAJAMARCA"&NOMBPROV=="JAEN"| NOMBDEP=="AMAZONAS"&NOMBPROV!="LUYA"|NOMBDEP=="AMAZONAS"&NOMBPROV!="CHACHAPOYAS"|NOMBDEP=="HUANUCO"&NOMBPROV=="MARAÑON"|NOMBDEP=="HUANUCO"&NOMBPROV=="LEONCIO PRADO"|NOMBDEP=="HUANUCO"&NOMBPROV=="PUERTO INCA"|NOMBDEP=="PASCO"&NOMBPROV=="OXAPAMPA"|NOMBDEP=="JUNIN"&NOMBPROV=="CHANCHAMAYO"|NOMBDEP=="JUNIN"&NOMBPROV=="SATIPO"|NOMBDEP=="CUSCO"&NOMBPROV==" LA CONVECION","Selva", ifelse(NOMBDEP=="HUANCAVELICA"|NOMBDEP=="LIMA"&NOMBPROV!="LIMA"|NOMBDEP=="HUANUCO"&NOMBPROV!="MARAÑON"|NOMBDEP=="HUANUCO"&NOMBPROV!="LEONCIO PRADO"|NOMBDEP=="HUANUCO"&NOMBPROV!="PUERTO INCA"|NOMBDEP=="PASCO"&NOMBPROV!="OXAPAMPA"|NOMBDEP=="JUNIN"&NOMBPROV!="CHANCHAMAYO"|NOMBDEP=="JUNIN"&NOMBPROV!="SATIPO","Centro", ifelse(NOMBDEP=="LIMA"&NOMBPROV=="LIMA"|NOMBDEP=="CALLAO","Lima Metropolitana",         ifelse(NOMBDEP=="ICA"|NOMBDEP=="AYACUCHO"|NOMBDEP=="AREQUIPA"|NOMBDEP=="MOQUEGUA"|NOMBDEP=="TACNA"|NOMBDEP=="PUNO"|NOMBDEP=="APURIMAC"|NOMBDEP=="CUSCO"&NOMBPROV!=" LA CONVENCION","Sur","Por definir"))))))
```

```{r}
rm(data_ubigeo_2022_innova)
```

```{r}
data_total <- data_syphilis%>% 
  left_join(data_ubigeo_macroregion, by = c("caseid","year"))

data_total <- data_total %>%
  left_join(departamentos, by = c("NOMBDEP"))
```

```{r}
rm(data_ubigeo_macroregion,data_ubigeo,data_syphilis)
```

```{r}
# Filtrar los datos
data_filtered <- data_total %>%
  mutate(
    syphilis_screening=ifelse(syphilis_screening=="Yes",1, 0)
  )

data_filtered$syphilis_screening <- ifelse(is.na(data_filtered$syphilis_screening),0,data_filtered$syphilis_screening)

data_filtered$NOMBDEP = as.factor(data_filtered$NOMBDEP)
data_filtered$year = as.factor(data_filtered$year)

data_filtered = data_filtered %>%
  filter(year!=2010&year!=2011)

# Crear el diseño de muestreo estratificado
design <- svydesign(id = ~ v001, strata = ~ v022, nest = TRUE, weights = ~ v005, data = data_filtered, na.rm = TRUE)

options(survey.lonely.psu="adjust")

syphilis_year<- svyby(~syphilis_screening,~NOMBDEP+year,svymean,design=design,na.rm=TRUE)
syphilis_total<- svyby(~syphilis_screening,~NOMBDEP,svymean,design=design,na.rm=TRUE)

syphilis_year = as.data.frame(syphilis_year)
syphilis_total = as.data.frame(syphilis_total)
```

```{r}
rm(design,data_filtered,data_total)
```

```{r}
data_grafico_total <- syphilis_total  %>%
  left_join(departamentos, by = c("NOMBDEP"))
```

Total
```{r}
ggplot() +
  geom_sf(data = data_grafico_total, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening total",
        fill = "Syphilis screening") 
```

```{r}
rm(data_grafico_total,syphilis_total)
```

```{r}
data_grafico_year <- syphilis_year  %>%
  left_join(departamentos, by = c("NOMBDEP"))
```

```{r}
rm(departamentos,provincias,syphilis_year)
```

2010
```{r}
data_grafico_2010 = data_grafico_year %>%
  filter(year==2010)

ggplot() +
  geom_sf(data = data_grafico_2010, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2010",
        fill = "Syphilis screening")
```
```{r}
rm(data_grafico_2010)
```

2011
```{r}
data_grafico_2011 = data_grafico_year %>%
  filter(year==2011)

ggplot() +
  geom_sf(data = data_grafico_2011, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2011",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2011)
```

2012
```{r}
data_grafico_2012 = data_grafico_year %>%
  filter(year==2012)

ggplot() +
  geom_sf(data = data_grafico_2012, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2012",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2012)
```

2013
```{r}
data_grafico_2013 = data_grafico_year %>%
  filter(year==2013)

ggplot() +
  geom_sf(data = data_grafico_2013, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2013",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2013)
```

2014
```{r}
data_grafico_2014 = data_grafico_year %>%
  filter(year==2014)

ggplot() +
  geom_sf(data = data_grafico_2014, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2014",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2014)
```

2015
```{r}
data_grafico_2015 = data_grafico_year %>%
  filter(year==2015)

ggplot() +
  geom_sf(data = data_grafico_2015, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2015",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2015)
```

2016
```{r}
data_grafico_2016 = data_grafico_year %>%
  filter(year==2016)

ggplot() +
  geom_sf(data = data_grafico_2016, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2016",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2016)
```

2017
```{r}
data_grafico_2017 = data_grafico_year %>%
  filter(year==2017)

ggplot() +
  geom_sf(data = data_grafico_2017, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2017",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2017)
```

2018
```{r}
data_grafico_2018 = data_grafico_year %>%
  filter(year==2018)

ggplot() +
  geom_sf(data = data_grafico_2018, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2018",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2018)
```

2019
```{r}
data_grafico_2019 = data_grafico_year %>%
  filter(year==2019)

ggplot() +
  geom_sf(data = data_grafico_2019, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2019",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2019)
```


2020
```{r}
data_grafico_2020 = data_grafico_year %>%
  filter(year==2020)

ggplot() +
  geom_sf(data = data_grafico_2020, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2020",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2020)
```

2021
```{r}
data_grafico_2021 = data_grafico_year %>%
  filter(year==2021)

ggplot() +
  geom_sf(data = data_grafico_2021, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2021",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2021)
```

2022
```{r}
data_grafico_2022 = data_grafico_year %>%
  filter(year==2022)

ggplot() +
  geom_sf(data = data_grafico_2022, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
   labs(title="Syphilis screening 2022",
        fill = "Syphilis screening")
```

```{r}
rm(data_grafico_2022)
```

```{r, fig.height=7, fig.width=9}
ggplot() +
  geom_sf(data = data_grafico_year, aes(geometry = geometry,fill = syphilis_screening), color = "white", size = 0.2) +
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
  facet_wrap(~year, nrow = 3)+
   labs(title="Syphilis screening 2012 - 2022",
        fill = "Syphilis screening") 
```

#####

Grafico dumbbell general
```{r}
ggplot(data_grafico_year, aes(x = syphilis_screening, y = NOMBDEP)) +
  geom_line() +
  geom_point(aes(color = year), size = 3) +
  xlab("Syphilis screening")+
  ylab("Region")
```

Grafico dumbbell 2012-2017
```{r}
d12_d17 = data_grafico_year %>%
  filter(year==2012|year==2013|year==2014|year==2015|year==2016|year==2017)
  
ggplot(d12_d17, aes(x = syphilis_screening, y = NOMBDEP)) +
  geom_line() +
  geom_point(aes(color = year), size = 3) +
  xlab("Syphilis screening")+
  ylab("Region")
```

Grafico dumbbell 2018-2022
```{r}
d18_d22 = data_grafico_year %>%
  filter(year==2018|year==2019|year==2020|year==2021|year==2022)
  
ggplot(d18_d22, aes(x = syphilis_screening, y = NOMBDEP)) +
  geom_line() +
  geom_point(aes(color = year), size = 3) +
  xlab("Syphilis screening")+
  ylab("Region")
```




