dataprep<-function(data){
  data %>% 
    select(caseid,
           qh95,
           qh106,
           v025,
           v024,
           v101,
           v102,
           v103,
           v136,
           v150,
           v001,
           v005,
           v022,
           v190,
           sregion,
           sprovincia,
           sdistri,
           longitudx,
           latitudy,
           m2a,
           m2b,
           m2c,
           m2d,
           m2e,
           m2f,
           m2g,
           m2h,
           m2i,
           m2j,
           m2k,
           m2l,
           m2m,
           m2n,
           m3a,
           m3b,
           m3c,
           m3d,
           m3e,
           m3f,
           m3g,
           m3h,
           m3i,
           m3j,
           m3k,
           m3l,
           m3m,
           m3n,
           m13,
           m14,
           m15,
           m17,
           m42a,
           m42b,
           m42c,
           m42d,
           m42e,
           m43,
           m44,
           m45,
           m46,
           m51a,
           m57e,
           m57f,
           m57g,
           m57h,
           m57i,
           m57j,
           m57k,
           m57l,
           m57m,
           m57n,
           m57o,
           m57p,
           m57q,
           m57r,
           m57x,
           m71,
           m72,
           v481,
           s410b,
           s411g,
           s411h,
           s411b,
           s411ba,
           s411ca,
           s411da,
           s411ea,
           s426fa,
           qi411_m,
           qi411f,
           bidx,
           b0,
           bd,
           b1,
           b2,
           b4,
           b11,
           b16,
           m18,
           m19,
           m19a,
           m70,
           m73,
           qs25bb,
           qs29a,
           qs601a,
           qs603,
           v201,
           v206,
           v207,
           v208,
           v213,
           v218,
           v219,
           v225,
           v228,
           v233,
           v238,
           v302,
           v313,
           v531,
           v532,
           v701,
           v730,
           v750,
           v761,
           v761b,
           v763a,
           v763b,
           v763c,
           v766b,
           v768a,
           v769,
           v770,
           v785,
           v830,
           v835a,
           v836,
           v012,
           v131,
           q220a,
           v437,
           v438,
           v445,
           v453,
           v454,
           v456,
           v457,
           v463a,
           v464,
           d104,
           d106,
           d107,
           d108,
           d115y,
           d116,
           d118a,
           d118y,
           d119y,
           s108n,
           s119d,
           s815aa,
           s815ab,
           s815ac,
           s815ad,
           s815ae,
           s815ax,
           s815az,
           s816aa,
           s816ab,
           s816ac,
           s816ad,
           s816ae,
           s816af,
           s816ag,
           s816ah,
           s816ai,
           s816aj,
           s816ak,
           s816al,
           s816aw,
           hv115,
           ha2,
           ha3,
           ha40,
           idx94,
           midx,
           hhid
    ) %>% 
    
    mutate(
      v005 = v005/1000000,
      
      juntos = case_when((qh95==1)~ "Yes",
                         (qh95==2)~ "No",
                         (qh95==3)~ "Don't know"),
      
      wawa_wasi = case_when((qh106==1)~ "Yes",
                            (qh106==2)~ "No",
                            (qh106==3)~ "Don't know"),
                               
      type_residence = ifelse(v025==1,"Urban","Rural"),
      
      departament = factor(v024, levels = c(1:25), labels = c("Amazonas","Ancash","Apurimac","Arequipa","Ayacucho",   
                                                             "Cajamarca","Callao","Cusco","Huancavelica","Huanuco",      
                                                             "Ica","Junin","La Libertad","Lambayeque","Lima",         
                                                             "Loreto","Madre De Dios","Moquegua","Pasco","Piura",     
                                                             "Puno","San Martin","Tacna","Tumbes","Ucayali")),
      
      childhood_place_residence = case_when((v103==0)~ "Capital",
                                            (v103==1)~ "City",
                                            (v103==2)~ "Town",
                                            (v103==3)~ "Countryside",
                                            (v103==4)~ "Abroad",
                                            TRUE     ~ "Don´t know"),
      
      members_household = case_when(is.na(v136)              ~ NA,
                                         (v136 < 5)          ~ "1-4",
                                         (v136 >=5 & v136 <7)~ "5-6",
                                          TRUE               ~ "MORE THAN 7"),
      
      relationship_household_head = case_when(is.na(v150)~ NA,
                                              (v150==1)~ "Head",
                                              (v150==2)~ "Wife",
                                              (v150==3)~ "Daugther",
                                              TRUE     ~ "Other"),
      
      wealth_index = factor(v190, levels = c(1:5), labels = c("Poorest","Poor","Middle","Rich","Richest")),
      
      natural_region = factor(sregion, levels = c(1:4), labels = c("Lima Metropolitan","Rest of Coast","Highland","Jungle")),
      
      prenatal_care_provider = case_when((m2a==1) ~ "Doctor",
                                         (m2c==1) ~ "Obstetrician",
                                         (m2b==1) ~ "Nurse",
                                         (m2d==1 | m2e==1 | m2f==1) ~ "technitian/other health provider",
                                         (m2g==1 | m2h==1 | m2k==1) ~ "Midwife/other",
                                         (m2n==1)~ "None"),
      
      prenatal_care_provider_childbirth = case_when((m3a==1) ~ "Doctor",
                                                    (m3c==1) ~ "Obstetrician",
                                                    (m3b==1) ~ "Nurse",
                                                    (m3d==1 | m3e==1 | m3f==1) ~ "technitian/other health provider",
                                                    (m3g==1 | m3h==1 | m3k==1) ~ "Midwife/other",
                                                    (m3n==1)~ "None"),
      
      first_prenatal_visit_1 = factor(m13,levels = c(0,1,2,3,4,5,6,7,8,9)),
      
      first_prenatal_visit_2 = case_when(is.na(v150)~ NA,
                                         (m13==0) ~ "0 month",
                                         (m13==1) ~ "Primer",
                                         (m13==2) ~ "Second",
                                         (m13==3) ~ "Third",
                                         TRUE ~ "More than third"),
      
      number_prenatal_visits_1 = factor(m14, levels = c (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)),
      
      number_prenatal_visits_2 = case_when(is.na(m14) ~ NA,
                                           (m14<=6) ~ "0-6",
                                           (m14>=7 & m14<=9) ~ "7-9",
                                           TRUE ~ "More than 9"),
      
      place_childbirth = case_when(is.na(m15) ~ NA,
                                   (m15==21 | m15==22 | m15==23) ~ "Hospital",
                                   (m15==24 | m15==25 | m15==26) ~ "Health center/post",
                                   (m15==31 | m15==32) ~ "Private",
                                   (m15==11 | m15==12) ~ "Midwife/home",
                                   TRUE ~ "Other"),
      
      caesarean = case_when((m17==0) ~ "No",
                            (m17==1) ~ "Yes"),
      
      basic_prenatal_care = (m42a+s411b+m42c+m42d+m42e+m43),
      basic_prenatal_care = case_when((basic_prenatal_care==0) ~ "None",
                                      (basic_prenatal_care==6) ~ "Complete",
                                      (basic_prenatal_care>6 & basic_prenatal_care<=47) ~ "Incomplete", 
                                      (basic_prenatal_care>=48) ~ "Don´t know"),
      
      iron_supplement = case_when(is.na(m45) ~ NA,
                                   (m45==0) ~ "No",
                                   (m45==1) ~ "Yes",
                                   (m45==8) ~ "Don´t know"),
      
      place_prenatal_care = case_when((m57e==1 | m57i==1 | m57j==1) ~ "Hospital",
                                     (m57f==1 | m57g==1 | m57k==1 | m57h==1) ~ "Health center/post/policlinic",
                                     (m57m==1 | m57n==1 | m57o==1 | m57r==1) ~ "Private",
                                     (m57l==1 | m57p==1 | m57q==1 | m57x==1) ~ "Other"),
      
      health_insurance = case_when((v481==0)~"No",
                                 (v481==1)~"Yes"),
      
      last_prenatal_visit = case_when((s410b==98) ~ NA),
      last_prenatal_visit = factor(s410b, levels = c(0,1,2,3,4,5,6,7,8,9)),
      
      syphilis_screening = case_when(is.na(s411g) ~ NA,
                                     (s411g==0) ~ "No",
                                     (s411g==1) ~ "Yes"
                                     (s411g==8) ~ "Don't know"),
      
      hiv_screening = case_when(is.na(s411h) ~ NA,
                                     (s411h==0) ~ "No",
                                     (s411h==1) ~ "Yes"
                                     (s411h==8) ~ "Don't know"),
      
      syphilis_screening_month = case_when((s411da==98) ~ NA),
      syphilis_screening_month = factor(s411da, levels = c(0,1,2,3,4,5,6,7,8,9)),
      
      hiv_screening_month = case_when((s411ea==98) ~ NA),
      hiv_screening_month = factor(s411ea, levels = c(0,1,2,3,4,5,6,7,8,9)),
      
      hepatitis_screening = case_when(is.na(qi411_m) ~ NA,
                                      (qi411_m==0) ~ "No",
                                      (qi411_m==1) ~ "Yes"
                                      (qi411_m==8) ~ "Don't know"),
      
      hepatitis_screening_month = case_when((qi411f==98) ~ NA),
      hepatitis_screening_month = factor(qi411f, levels = c(0,1,2,3,4,5,6,7,8,9)),
      
      single_multiple_delivery = case_when(is.na(qi411_m) ~ NA,
                                           (b0==0) ~ "Single",
                                           TRUE ~ "Multiple"),
      
      sex_child = as.factor(ifelse(b4 == 1,"Masculino","Femenino")),
      
      size_birth = case_when ((m18==1) ~ "very large",
                              (m18==2) ~ "large",
                              (m18==3) ~ "normal",
                              (m18==4) ~ "small",
                              (m18==5) ~ "very_small",
                              (m18==8) ~ NA),
      
      weight_birth = case_when((m19>=2500) ~ "normal",
                               (m19<2500) ~ "low",
                               (m19==9996 | m19==9998) ~ NA),
      
      age_mother = ifelse(v012<19,"15-19",
                          ifelse(v012>19 & v012<25, "20-24",
                              ifelse(v012>=25&v012<30,"25-30",
                                  ifelse(v012>=30&v012<35,"30-35",
                                      ifelse(v012>=35,"35 more",NA))))),
      
      ethnicity = case_when(is.na(v131) ~ NA,
                            (v131==10) ~ "Spanish",
                            (v131==1) ~ "Quechua",
                            (v131==2) ~ "Aimara",
                            (v131==11 | v131==12) ~ "Foreigner",
                            TRUE ~ "Other indigenous"),
      
      
      marital_status = ifelse(hv115==0,"Single", 
                                      ifelse(hv115==1|hv115==2,"Married/living_together", 
                                             ifelse(hv115>=3,"Widowed/Divorced/Separated",NA))),
      
      education_level = ifelse(s108n==0,"None/Preschool",
                         ifelse(s108n==1,"Primary",
                                ifelse(s108n==2,"Secondary",
                                       ifelse(s108n>=3&s108n<6,"Higher",NA)))),
      
      education_level_partner = case_when(is.na(v701) ~ NA,
                                          (v701==0) ~ "None",
                                          (v701==1) ~ "Primary",
                                          (v701==2) ~ "Secondary",
                                          (v701==8) ~ "Don´t know"),
      
      know_syphilis = case_when((s815aa==0) ~ "No",
                                (s815aa==1) ~ "Yes"),
      
      know_other_sti = (s815ab+s815ac+s815ad+s815ae+s815ax), know_other_sti=case_when(know_other_sti==0~"None",
                                                                                      know_other_sti==1~"At least one",
                                                                                      know_other_sti>=2~"More than one"),
      
      know_sti_symptoms = (s816aa+s816ab+s816ab+s816ad+s816ae+s816af+s816ag+s816ah+s816ai+s816aj+s816ak+s816al+s816aw), 
      know_sti_symptoms = case_when(know_sti_symptoms==0~"NO",
                                    know_sti_symptoms==1~"At least one",
                                    know_sti_symptoms>=2~"More than one"),
      
      emotional_violence = factor(d104, levels = c(0,1), labels = c("No", "Yes")),
      
      minor_physical_violence = factor(d106, levels = c(0,1), labels = c("No", "Yes")),
      
      severe_physical_violence = factor(d107, levels = c(0,1), labels = c("No", "Yes")),
      
      sexual_physical_violence = factor(d108, levels = c(0,1), labels = c("No", "Yes")), 
      
      physical_violence_pregnancy_partner = factor(d118a, levels = c(0,1), labels = c("No", "Yes")),
      
      physical_violence_pregnancy = factor(d118y, levels = c(0,1), labels = c("Yes","No")),
      
      assistance_violence_sought = factor(d119y, levels = c(0,1), labels = c("Yes","No")),
      
      diagnosted_sti_12months = factor(v763a, levels = c(0,1,8), labels = c("No","Yes","Dont Know")),
      
      have_sti_symptoms = case_when((v763b==1 & v763c==0)~"Only sore/ulcer",
                                  (v763b==1 & v763c==8)~"Only sore/ulcer",
                                  (v763b==0 & v763c==1)~"Only flow",
                                  (v763b==8 & v763c==1)~"Only flow",
                                  (v763b==1 & v763c==1)~"Both",
                                  ((v763b==0 & v763c==0) | (V763B==8 & v763c==8) | (V763B==8 & v763c==0) | (V763B==0 & v763c==8))~"None"),
      
      TOTAL_CHILDREN = factor(V201, levels = c (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)),
      
      UNDER_SIXYEARS_CHILDREN =factor(V208, levels = c(1,2,3,4))
      
     ) %>%  rename(year_birth = b2)
}