---
title: "Home, prenatal care"
author: "Jazmín Qquellon"
date: "2023-07-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(readr)
library(tidyverse)
library(survey)
library(dplyr)
data <- read_csv("Data_final/data_syphilis.csv")

data <- data %>%
   mutate(size_final = case_when(
      size_birth == "large"| size_birth == "very large"  ~ "large/very large",
      size_birth == "normal" ~ "normal",
      size_birth == "small"| size_birth == "very_small"  ~ "small/very small",
      TRUE ~ NA
    ))
```

```{r}
# Crear el diseño de muestreo estratificado y anidado
design_total <- svydesign(id = ~ v001, strata = ~ v022, nest = TRUE, weights = ~ v005, data = data)

options(survey.lonely.psu="adjust")
```

```{r}
#2010
data_filtered_2010 <- data %>%
  filter(year==2010)

# Crear el diseño de muestreo estratificado y anidado
design_2010 <- svydesign(id = ~ v001, strata = ~ v022, nest = TRUE, weights = ~ v005, data = data_filtered_2010)

options(survey.lonely.psu="adjust")

#2016
data_filtered_2016 <- data %>%
  filter(year==2016)

# Crear el diseño de muestreo estratificado y anidado
design_2016 <- svydesign(id = ~ v001, strata = ~ v022, nest = TRUE, weights = ~ v005, data = data_filtered_2016)

options(survey.lonely.psu="adjust")

#2022
data_filtered_2022 <- data %>%
  filter(year==2022)

# Crear el diseño de muestreo estratificado y anidado
design_2022 <- svydesign(id = ~ v001, strata = ~ v022, nest = TRUE, weights = ~ v005, data = data_filtered_2022)

options(survey.lonely.psu="adjust")
```


```{r}
#TIPO DE RESIDENCIA
residence_total = svymean(~ifelse(is.na(type_residence),"NA",type_residence), design=design_total)

residence_total_1 = residence_total*100
residence_total_2 = confint(residence_total)

residence_total = data.frame(residence_total_1,residence_total_2*100)
rm(residence_total_1,residence_total_2)

#RESIDENCIA 2010 
residence_2010 <- svymean(~ifelse(is.na(type_residence),"NA",type_residence), design_2010)

residence_2010_1 = residence_2010*100
residence_2010_2 = confint(residence_2010)

residence_2010 = data.frame(residence_2010_1,residence_2010_2*100)
rm(residence_2010_1,residence_2010_2)

#RESIDENCIA 2016 
residence_2016 <- svymean(~ifelse(is.na(type_residence),"NA",type_residence), design_2016)

residence_2016_1 = residence_2016*100
residence_2016_2 = confint(residence_2016)

residence_2016 = data.frame(residence_2016_1,residence_2016_2*100)
rm(residence_2016_1,residence_2016_2)

#RESIDENCIA 2022
residence_2022 <- svymean(~ifelse(is.na(type_residence),"NA",type_residence), design_2022)

residence_2022_1 = residence_2022*100
residence_2022_2 = confint(residence_2022)

residence_2022 = data.frame(residence_2022_1,residence_2022_2*100)
rm(residence_2022_1,residence_2022_2)
```

```{r}
rm(residence_total,residence_2010,residence_2016,residence_2022)
```

```{r}
#Natural region
natural_total <- svymean(~ifelse(is.na(natural_region),"NA",natural_region), design=design_total)

natural_total_1 = natural_total*100
natural_total_2 = confint(natural_total)

natural_total = data.frame(natural_total_1,natural_total_2*100)
rm(natural_total_1,natural_total_2)

#NATURAL 2010 
natural_2010 <- svymean(~ifelse(is.na(natural_region),"NA",natural_region), design_2010)

natural_2010_1 = natural_2010*100
natural_2010_2 = confint(natural_2010)

natural_2010 = data.frame(natural_2010_1,natural_2010_2*100)
rm(natural_2010_1,natural_2010_2)

#NATURAL 2016 
natural_2016 <- svymean(~ifelse(is.na(natural_region),"NA",natural_region), design_2016)

natural_2016_1 = natural_2016*100
natural_2016_2 = confint(natural_2016)

natural_2016 = data.frame(natural_2016_1,natural_2016_2*100)
rm(natural_2016_1,natural_2016_2)

#NATURAL 2022
natural_2022 <- svymean(~ifelse(is.na(natural_region),"NA",natural_region), design_2022)

natural_2022_1 = natural_2022*100
natural_2022_2 = confint(natural_2022)

natural_2022 = data.frame(natural_2022_1,natural_2022_2*100)
rm(natural_2022_1,natural_2022_2)

```

```{r}
rm(natural_total,natural_2010, natural_2016, natural_2022)
```

```{r}
#Wealth index
wi_total <- svymean(~ifelse(is.na(wealth_index),"NA",wealth_index), design=design_total)

wi_total_1 = wi_total*100
wi_total_2 = confint(wi_total)

wi_total = data.frame(wi_total_1,wi_total_2*100)
rm(wi_total_1,wi_total_2)

#WI 2010 
wi_2010 <- svymean(~ifelse(is.na(wealth_index),"NA",wealth_index), design_2010)

wi_2010_1 = wi_2010*100
wi_2010_2 = confint(wi_2010)

wi_2010 = data.frame(wi_2010_1,wi_2010_2*100)
rm(wi_2010_1,wi_2010_2)

#WI 2016 
wi_2016 <- svymean(~ifelse(is.na(wealth_index),"NA",wealth_index), design_2016)

wi_2016_1 = wi_2016*100
wi_2016_2 = confint(wi_2016)

wi_2016 = data.frame(wi_2016_1,wi_2016_2*100)
rm(wi_2016_1,wi_2016_2)

#WI 2022
wi_2022 <- svymean(~ifelse(is.na(wealth_index),"NA",wealth_index), design_2022)

wi_2022_1 = wi_2022*100
wi_2022_2 = confint(wi_2022)

wi_2022 = data.frame(wi_2022_1,wi_2022_2*100)
rm(wi_2022_1,wi_2022_2)
```

```{r}
rm(wi_total,wi_2010, wi_2016, wi_2022)
```

```{r}
#Relationship with household head

#Total
household_total <- svymean(~ifelse(is.na(relationship_household_head),"NA",relationship_household_head), design=design_total)

household_total_1 = household_total*100
household_total_2 = confint(household_total)

household_total = data.frame(household_total_1,household_total_2*100)
rm(household_total_1,household_total_2)

#HOUSEHOLD 2010 
household_2010 <- svymean(~ifelse(is.na(relationship_household_head),"NA",relationship_household_head), design_2010)

household_2010_1 = household_2010*100
household_2010_2 = confint(household_2010)

household_2010 = data.frame(household_2010_1,household_2010_2*100)
rm(household_2010_1,household_2010_2)

#HOUSEHOLD 2016 
household_2016 <- svymean(~ifelse(is.na(relationship_household_head),"NA",relationship_household_head), design_2016)

household_2016_1 = household_2016*100
household_2016_2 = confint(household_2016)

household_2016 = data.frame(household_2016_1,household_2016_2*100)
rm(household_2016_1,household_2016_2)

#HOUSEHOLD 2022
household_2022 <- svymean(~ifelse(is.na(relationship_household_head),"NA",relationship_household_head), design_2022)

household_2022_1 = household_2022*100
household_2022_2 = confint(household_2022)

household_2022 = data.frame(household_2022_1,household_2022_2*100)
rm(household_2022_1,household_2022_2)

```

```{r}
rm(household_total,household_2010, household_2016, household_2022)
```

```{r}
#Total members household

#Total
members_total <- svymean(~ifelse(is.na(members_household),"NA",members_household),design=design_total)

members_total_1 = members_total*100
members_total_2 = confint(members_total)

members_total = data.frame(members_total_1,members_total_2*100)
rm(members_total_1,members_total_2)

#MEMBERS 2010 
members_2010 <- svymean(~ifelse(is.na(members_household),"NA",members_household), design_2010)

members_2010_1 = members_2010*100
members_2010_2 = confint(members_2010)

members_2010 = data.frame(members_2010_1,members_2010_2*100)
rm(members_2010_1,members_2010_2)

#MEMBERS 2016 
members_2016 <- svymean(~ifelse(is.na(members_household),"NA",members_household), design_2016)

members_2016_1 = members_2016*100
members_2016_2 = confint(members_2016)

members_2016 = data.frame(members_2016_1,members_2016_2*100)
rm(members_2016_1,members_2016_2)

#MEMBERS 2022
members_2022 <- svymean(~ifelse(is.na(members_household),"NA",members_household), design_2022)

members_2022_1 = members_2022*100
members_2022_2 = confint(members_2022)

members_2022 = data.frame(members_2022_1,members_2022_2*100)
rm(members_2022_1,members_2022_2)

```

```{r}
rm(members_total,members_2010, members_2016, members_2022)
```

```{r}
#Social programs: Juntos

#Total
#juntos_total <- svymean(~ifelse(is.na(juntos),"NA",juntos),design=design_total)
juntos_total <- svymean(~juntos, design=design_total,na.rm=TRUE)

juntos_total_1 = juntos_total*100
juntos_total_2 = confint(juntos_total)

juntos_total = data.frame(juntos_total_1,juntos_total_2*100)
rm(juntos_total_1,juntos_total_2)

#JUNTOS 2010 
#juntos_2010 <- svymean(~juntos, design_2010,na.rm=TRUE)

#juntos_2010_1 = juntos_2010*100
#juntos_2010_2 = confint(juntos_2010)

#juntos_2010 = data.frame(juntos_2010_1,juntos_2010_2*100)
#rm(juntos_2010_1,juntos_2010_2)

#JUNTOS 2016 
juntos_2016 <- svymean(~ifelse(is.na(juntos),"NA",juntos), design_2016)

juntos_2016_1 = juntos_2016*100
juntos_2016_2 = confint(juntos_2016)

juntos_2016 = data.frame(juntos_2016_1,juntos_2016_2*100)
rm(juntos_2016_1,juntos_2016_2)

#JUNTOS 2022
juntos_2022 <- svymean(~ifelse(is.na(juntos),"NA",juntos), design_2022)

juntos_2022_1 = juntos_2022*100
juntos_2022_2 = confint(juntos_2022)

juntos_2022 = data.frame(juntos_2022_1,juntos_2022_2*100)
rm(juntos_2022_1,juntos_2022_2)
```

```{r}
rm(juntos_total,juntos_2010, juntos_2016, juntos_2022)
```

```{r}
#Social programs: Wawa wasi

wawa_total <- svymean(~wawa_wasi, design=design_total,na.rm=TRUE)

wawa_total_1 = wawa_total*100
wawa_total_2 = confint(wawa_total)

wawa_total = data.frame(wawa_total_1,wawa_total_2*100)
rm(wawa_total_1,wawa_total_2)

#WAWA 2010 
#wawa_2010 <- svymean(~wawa_wasi, design_2010,na.rm=TRUE)

#wawa_2010_1 = wawa_2010*100
#wawa_2010_2 = confint(wawa_2010)

#wawa_2010 = data.frame(wawa_2010_1,wawa_2010_2*100)
#rm(wawa_2010_1,wawa_2010_2)

#WAWA 2016 
wawa_2016 <- svymean(~ifelse(is.na(wawa_wasi),"NA",wawa_wasi), design_2016)

wawa_2016_1 = wawa_2016*100
wawa_2016_2 = confint(wawa_2016)

wawa_2016 = data.frame(wawa_2016_1,wawa_2016_2*100)
rm(wawa_2016_1,wawa_2016_2)

#WAWA 2022
wawa_2022 <- svymean(~ifelse(is.na(wawa_wasi),"NA",wawa_wasi), design_2022)

wawa_2022_1 = wawa_2022*100
wawa_2022_2 = confint(wawa_2022)

wawa_2022 = data.frame(wawa_2022_1,wawa_2022_2*100)
rm(wawa_2022_1,wawa_2022_2)

```

```{r}
rm(wawa_total,wawa_2010, wawa_2016, wawa_2022)
```

```{r}
#Health insurance

#Total
insurance_total <- svymean(~ifelse(is.na(health_insurance),"NA",health_insurance), design=design_total)

insurance_total_1 = insurance_total*100
insurance_total_2 = confint(insurance_total)

insurance_total = data.frame(insurance_total_1,insurance_total_2*100)
rm(insurance_total_1,insurance_total_2)

#INSURANCE 2010 
insurance_2010 <- svymean(~ifelse(is.na(health_insurance),"NA",health_insurance), design_2010)

insurance_2010_1 = insurance_2010*100
insurance_2010_2 = confint(insurance_2010)

insurance_2010 = data.frame(insurance_2010_1,insurance_2010_2*100)
rm(insurance_2010_1,insurance_2010_2)

#INSURANCE 2016 
insurance_2016 <- svymean(~ifelse(is.na(health_insurance),"NA",health_insurance), design_2016)

insurance_2016_1 = insurance_2016*100
insurance_2016_2 = confint(insurance_2016)

insurance_2016 = data.frame(insurance_2016_1,insurance_2016_2*100)
rm(insurance_2016_1,insurance_2016_2)

#INSURANCE 2022
insurance_2022 <- svymean(~ifelse(is.na(health_insurance),"NA",health_insurance), design_2022)

insurance_2022_1 = insurance_2022*100
insurance_2022_2 = confint(insurance_2022)

insurance_2022 = data.frame(insurance_2022_1,insurance_2022_2*100)
rm(insurance_2022_1,insurance_2022_2)
```

```{r}
rm(insurance_total,insurance_2010, insurance_2016, insurance_2022)
```

```{r}
#place of prenatal care

#Total
place_total <- svymean(~ifelse(is.na(place_prenatal_care),"NA",place_prenatal_care), design=design_total)

place_total_1 = place_total*100
place_total_2 = confint(place_total)

place_total = data.frame(place_total_1,place_total_2*100)
rm(place_total_1,place_total_2)

#PLACE 2010 
place_2010 <- svymean(~ifelse(is.na(place_prenatal_care),"NA",place_prenatal_care), design_2010)

place_2010_1 = place_2010*100
place_2010_2 = confint(place_2010)

place_2010 = data.frame(place_2010_1,place_2010_2*100)
rm(place_2010_1,place_2010_2)

#PLACE 2016 
place_2016 <- svymean(~ifelse(is.na(place_prenatal_care),"NA",place_prenatal_care), design_2016)

place_2016_1 = place_2016*100
place_2016_2 = confint(place_2016)

place_2016 = data.frame(place_2016_1,place_2016_2*100)
rm(place_2016_1,place_2016_2)

#PLACE 2022
place_2022 <- svymean(~ifelse(is.na(place_prenatal_care),"NA",place_prenatal_care), design_2022)

place_2022_1 = place_2022*100
place_2022_2 = confint(place_2022)

place_2022 = data.frame(place_2022_1,place_2022_2*100)
rm(place_2022_1,place_2022_2)
```

```{r}
rm(place_total,place_2010, place_2016, place_2022)
```

```{r}
#professional level of prenatal care

#Total
provider_total <- svymean(~ifelse(is.na(prenatal_care_provider),"NA",prenatal_care_provider), design=design_total)

provider_total_1 = provider_total*100
provider_total_2 = confint(provider_total)

provider_total = data.frame(provider_total_1,provider_total_2*100)
rm(provider_total_1,provider_total_2)

#PROVIDER 2010 
provider_2010 <- svymean(~ifelse(is.na(prenatal_care_provider),"NA",prenatal_care_provider), design_2010)

provider_2010_1 = provider_2010*100
provider_2010_2 = confint(provider_2010)

provider_2010 = data.frame(provider_2010_1,provider_2010_2*100)
rm(provider_2010_1,provider_2010_2)

#PROVIDER 2016 
provider_2016 <- svymean(~ifelse(is.na(prenatal_care_provider),"NA",prenatal_care_provider), design_2016)

provider_2016_1 = provider_2016*100
provider_2016_2 = confint(provider_2016)

provider_2016 = data.frame(provider_2016_1,provider_2016_2*100)
rm(provider_2016_1,provider_2016_2)

#PROVIDER 2022
provider_2022 <- svymean(~ifelse(is.na(prenatal_care_provider),"NA",prenatal_care_provider), design_2022)

provider_2022_1 = provider_2022*100
provider_2022_2 = confint(provider_2022)

provider_2022 = data.frame(provider_2022_1,provider_2022_2*100)
rm(provider_2022_1,provider_2022_2)
```

```{r}
rm(provider_total, provider_2010, provider_2016, provider_2022)
```

```{r}
#Size of child at birth

#Total
size_total <- svymean(~ifelse(is.na(size_final),"NA",size_final), design=design_total)

size_total_1 = size_total*100
size_total_2 = confint(size_total)

size_total = data.frame(size_total_1,size_total_2*100)
rm(size_total_1,size_total_2)

#SIZE 2010 
size_2010 <- svymean(~ifelse(is.na(size_final),"NA",size_final), design_2010)

size_2010_1 = size_2010*100
size_2010_2 = confint(size_2010)

size_2010 = data.frame(size_2010_1,size_2010_2*100)
rm(size_2010_1,size_2010_2)

#SIZE 2016 
size_2016 <- svymean(~ifelse(is.na(size_final),"NA",size_final), design_2016)

size_2016_1 = size_2016*100
size_2016_2 = confint(size_2016)

size_2016 = data.frame(size_2016_1,size_2016_2*100)
rm(size_2016_1,size_2016_2)

#SIZE 2022
size_2022 <- svymean(~ifelse(is.na(size_final),"NA",size_final), design_2022)

size_2022_1 = size_2022*100
size_2022_2 = confint(size_2022)

size_2022 = data.frame(size_2022_1,size_2022_2*100)
rm(size_2022_1,size_2022_2)
```

```{r}
rm(size_total, size_2010, size_2016, size_2022)
```

```{r}
#Weight of child at birth

#Total
weight_total <- svymean(~ifelse(is.na(weight_birth),"NA",weight_birth), design=design_total)

weight_total_1 = weight_total*100
weight_total_2 = confint(weight_total)

weight_total = data.frame(weight_total_1,weight_total_2*100)
rm(weight_total_1,weight_total_2)

#WEIGHT 2010 
weight_2010 <- svymean(~ifelse(is.na(weight_birth),"NA",weight_birth), design_2010)

weight_2010_1 = weight_2010*100
weight_2010_2 = confint(weight_2010)

weight_2010 = data.frame(weight_2010_1,weight_2010_2*100)
rm(weight_2010_1,weight_2010_2)

#WEIGHT 2016 
weight_2016 <- svymean(~ifelse(is.na(weight_birth),"NA",weight_birth), design_2016)

weight_2016_1 = weight_2016*100
weight_2016_2 = confint(weight_2016)

weight_2016 = data.frame(weight_2016_1,weight_2016_2*100)
rm(weight_2016_1,weight_2016_2)

#WEIGHT 2022
weight_2022 <- svymean(~ifelse(is.na(weight_birth),"NA",weight_birth), design_2022)

weight_2022_1 = weight_2022*100
weight_2022_2 = confint(weight_2022)

weight_2022 = data.frame(weight_2022_1,weight_2022_2*100)
rm(weight_2022_1,weight_2022_2)
```

```{r}
rm(weight_total, weight_2010, weight_2016, weight_2022)
```

```{r}
#MONTHS OF THE FIRST PRENATAL VISIT
month_total <- svyquantile(~first_prenatal_visit_1, design=design_total,na.rm=TRUE, c(.25,.5,.75))
print(month_total)

#MONTH 2010 
month_2010 <- svyquantile(~first_prenatal_visit_1, design_2010,na.rm=TRUE, c(.25,.5,.75))
print(month_2010)

#MONTH 2016 
month_2016 <- svyquantile(~first_prenatal_visit_1, design_2016,na.rm=TRUE, c(.25,.5,.75))
print(month_2016)

#MONTH 2022
month_2022 <- svyquantile(~first_prenatal_visit_1, design_2022,na.rm=TRUE, c(.25,.5,.75))
print(month_2022)
```

```{r}
rm(month_total,month_2010, month_2016, month_2022)
```

```{r}
#NUMBER OF THE PRENATAL VISITS

number_total <- svyquantile(~number_prenatal_visits_1, design=design_total,na.rm=TRUE, c(.25,.5,.75))
print(number_total)

#NUMBER 2010 
number_2010 <- svyquantile(~number_prenatal_visits_1, design_2010,na.rm=TRUE, c(.25,.5,.75))
print(number_2010)

#NUMBER 2016 
number_2016 <- svyquantile(~number_prenatal_visits_1, design_2016,na.rm=TRUE, c(.25,.5,.75))
print(number_2016)

#NUMBER 2022
number_2022 <- svyquantile(~number_prenatal_visits_1, design_2022,na.rm=TRUE, c(.25,.5,.75))
print(number_2022)
```

```{r}
rm(number_total,number_2010, number_2016, number_2022)
```

